#!/bin/bash
#
# First, make sure you have a .env file with the following content:
#
#   export RABBITMQ_URI=
#   export S3_BUCKET_NAME=
#   export AWS_ACCESS_KEY_ID=
#   export AWS_SECRET_ACCESS_KEY=
#
# With the variable values set, of course. Then, run the Docker image with:
#
#   run <tag>
#
# Where <tag> is one of the available tags, see:
# https://hub.docker.com/r/stormysmoke/sent2vec-back/tags/
#------------------------------------------------------------------------------#

set -e

source .env

[[ -z "$RABBITMQ_URI" || -z "$S3_BUCKET_NAME" || -z "$AWS_ACCESS_KEY_ID" || -z "$AWS_SECRET_ACCESS_KEY" ]] &&
{ echo "Set variables in .env file first." && exit 1; }

docker run \
  -d \
  -e RABBITMQ_URI="$RABBITMQ_URI" \
  -e S3_BUCKET_NAME="$S3_BUCKET_NAME" \
  -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
  -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
  stormysmoke/sent2vec-back:"$1"
