#!/bin/bash

docker run \
  -d \
  -e RABBITMQ_URI="$RABBITMQ_URI" \
  -e S3_BUCKET_NAME="$S3_BUCKET_NAME" \
  -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
  -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
  stormysmoke/sent2vec-back:"$1"
